#! /bin/bash
### Lift temporary bans script ###
# Run this script once a day by
# a cronjob.
# Written by tobi-the-fraggel

# Location of tembans file
TARGET="/home/pradmin/pr_servers/fcv/mods/pr/settings/banlist.txt"

# Getting todays date
DATE=$(date -I)

# Retrieving hash key from tempban file
HASH=$(grep "$DATE" $TARGET | cut -d' ' -f2)

# Check if there is a key to be removed and if not do nothing
if [ -z "$HASH" ]; then
	echo -e "No key to be removed today.\nExiting Script." > test.log
	exit 1
fi

# Removing hash from banlist and from tempban file
echo "$HASH has been removed"
sed -i "/${DATE}/d" $TARGET
screen -x fcv -X stuff "admin.removeKeyFromBanList $HASH"$(echo -ne '\015')
