#! /bin/bash
### Automated removal of temporary bans ###
# Run this script once a day by a cronjob.
# Uncomment the 2 'echo' commands to test
# script functionality.
#
### Written by tobi-the-fraggel ###


#######################################################################
### Server Variables / Adjust to your needs ###########################
#
# Absolute path to scheduled bans file. Call it banlist.txt?
TEMPBAN="/path/to/your/banlist.txt"
#
#######################################################################

# Constants
DATE=$(date -I)
HASH=$(grep "$DATE" "$TEMPBAN" | cut -d' ' -f2)

# Check if there is a key for removal and if not leave script.
if [ -z "$HASH" ]
	then
		#echo -e "No key found matching current date.\nExiting Script."
		exit 1
fi

# Removing hash from banlist and from tempban file
sed -i "/${DATE}/d" "$TEMPBAN"
screen -x fcv -X stuff "admin.removeKeyFromBanList $HASH"$(echo -ne '\015')
#echo "$HASH has been removed"