#!/bin/bash
### Remove hashkey from banlist through a running PR console ###
# Execute script name and enter player hash as an argument
# to add key to the banlist.
# I recommend to put the script in ~/bin and add ~/bin to $PATH
# Usage: ban <hash>
# 
### Written by tobi-the-fraggel and Cisco ###

########################################################################
### Server Variables / Adjust to your needs ############################
#
# Absolute path to scheduled bans file. Call it banlist.txt?
TEMPBAN="/path/to/your/banlist.txt"
#
########################################################################

# Constants
HASH=$1
LENGTH=$(echo $1 | wc -m)

# Test if hash is a legit value.
if [  $LENGTH -ne 33 ]
	then
		echo "Usage: ./unban.sh \"hash\""
		echo "Length of hash is not correct. Did you copy the entire hash?"
		exit 1
# In case of a scheduled ban, this removes it.
elif [[ -z $(grep "$1" "$TEMPBAN") ]]
	then
		echo -e "Removing $1 from time table.\nScheduled ban is lifted."
		sed -i '/${$1}/d' "$TEMPBAN"
	else
		echo -e "No scheduled ban found in $TEMPBAN\nRemoving $1 from banlist."
fi


# Send command to screen session
screen -x fcv -X stuff "admin.removeKeyFromBanList $1"$(echo -ne '\015')