#!/bin/bash
### Remove hashkey from banlist through a running PR console ###
# Execute script name and enter player hash as an argument
# to add key to the banlist.
# I recommend to put the script in ~/bin and add ~/bin to $PATH
# Usage: ban <hash>
# 
### Written by tobi-the-fraggel and Cisco ###
source config.sh

# Variables
hash=$1
length=$(echo $hash | wc -m)

# Test if hash is a legit value.
if [  $length -ne 33 ]
	then
		echo "Usage: unban <hash>"
		echo "Length of hash is not correct. Did you copy the entire hash?"
		exit 1
# In case of a scheduled ban, this removes it.
elif [ -z "$(grep "$hash" "$TEMPBAN")" ]
	then
		echo -e "Removing $hash from time table.\nScheduled ban is lifted."
		sed -i '/${$hash}/d' "$TEMPBAN"
	else
		echo -e "No scheduled ban found in $TEMPBAN\nRemoving $hash from banlist."
fi


# Send command to screen session
screen -x "$SCREEN" -X stuff "admin.removeKeyFromBanList $hash"$(echo -ne '\015')